on:
  schedule:
   - cron: '0 10 * * *'
  workflow_dispatch:

name: calendar_flow

jobs:
  run-r-script:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Execute calendar
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
        run: |
          Rscript "monotri_bot.R"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo users" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
